import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";



const gilroy = localFont({
  src: [
    {
      path: "../public/fonts/Gilroy-Bold.ttf",
      weight: "800",
      style: "bold"
    },
    {
      path: "../public/fonts/Gilroy-Regular.ttf",
      weight: "400",
      style: "normal"
    }
  ],
  variable: "--font-gilroy"
});


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${gilroy.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
